FROM ghcr.io/mostlygeek/llama-swap:cuda

WORKDIR /app

COPY --chmod=755 docker/quickpod-entrypoint.sh /app/quickpod-entrypoint
COPY --chmod=755 docker/llama-server-progress.sh /app/llama-server-progress
COPY quickpod.config.yaml /app/config.yaml
COPY think.gbnf /app/think.gbnf

ENTRYPOINT [ "/app/quickpod-entrypoint" ]
