healthCheckTimeout: 300
logRequests: true
logToStdout: both
startPort: 9000
apiKeys:
  - "${env.LS_KEY}"

macros:
  LLAMA_SERVER: /app/llama-server-progress
  COMMON_ARGS: >-
    -ngl 99 -np 1 -c 262144 -fa on
    --cache-type-k q4_0 --cache-type-v q4_0
    --top-k 20 --repeat_penalty 1.0
  QWEN35_35B_A3B_COMMON_ARGS: >-
    -hf unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL.gguf
    -ngl 999
    --fit off
    -fa on
    -ctk q4_0
    -ctv q4_0
    -b 2048
    -ub 512
    --parallel 1
    --no-mmap

models:
  qwen35-27b-unsloth:
    cmd: >
      ${LLAMA_SERVER}
      -hf unsloth/Qwen3.5-27B-GGUF:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 0.6 --top-p 0.95 --min-p 0.00 --presence_penalty 0.0

  qwen35-27b-claude46-reasoning:
    cmd: >
      ${LLAMA_SERVER}
      -hf Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 0.6 --top-p 0.95 --min-p 0.00 --presence_penalty 0.0

  qwen35-27b-hauhau-uncensored:
    cmd: >
      ${LLAMA_SERVER}
      -hf HauhauCS/Qwen3.5-27B-Uncensored-HauhauCS-Aggressive:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 0.6 --top-p 0.95 --presence_penalty 0.0

  qwen35-27b-unsloth-no-thinking:
    cmd: >
      ${LLAMA_SERVER}
      -hf unsloth/Qwen3.5-27B-GGUF:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 1.0 --top-p 0.95 --min-p 0.00 --presence_penalty 1.5
      --chat-template-kwargs '{"enable_thinking":false}'

  qwen35-27b-claude46-no-thinking:
    cmd: >
      ${LLAMA_SERVER}
      -hf Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 1.0 --top-p 0.95 --min-p 0.00 --presence_penalty 1.5
      --chat-template-kwargs '{"enable_thinking":false}'

  qwen35-27b-hauhau-uncensored-no-thinking:
    cmd: >
      ${LLAMA_SERVER}
      -hf HauhauCS/Qwen3.5-27B-Uncensored-HauhauCS-Aggressive:Q4_K_M
      --port ${PORT}
      --alias ${MODEL_ID}
      ${COMMON_ARGS}
      --temp 0.7 --top-p 0.8 --presence_penalty 1.5
      --chat-template-kwargs '{"enable_thinking":false}'

  qwen35-35b-a3b-262k:
    cmd: >
      ${LLAMA_SERVER}
      ${QWEN35_35B_A3B_COMMON_ARGS}
      --port ${PORT}
      --alias ${MODEL_ID}
      -c 262144

  qwen35-35b-a3b-1m:
    cmd: >
      ${LLAMA_SERVER}
      ${QWEN35_35B_A3B_COMMON_ARGS}
      --port ${PORT}
      --alias ${MODEL_ID}
      -c 1048576
      --override-kv "qwen35moe.context_length=int:1048576"
      --rope-scaling yarn
      --rope-scale 4.0
      --yarn-orig-ctx 262144
